/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KeychainsRouteImport } from './routes/keychains'
import { Route as HairAccessoriesRouteImport } from './routes/hair-accessories'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as BouquetsRouteImport } from './routes/bouquets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'

const KeychainsRoute = KeychainsRouteImport.update({
  id: '/keychains',
  path: '/keychains',
  getParentRoute: () => rootRouteImport,
} as any)
const HairAccessoriesRoute = HairAccessoriesRouteImport.update({
  id: '/hair-accessories',
  path: '/hair-accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const BouquetsRoute = BouquetsRouteImport.update({
  id: '/bouquets',
  path: '/bouquets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bouquets': typeof BouquetsRoute
  '/custom': typeof CustomRoute
  '/hair-accessories': typeof HairAccessoriesRoute
  '/keychains': typeof KeychainsRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bouquets': typeof BouquetsRoute
  '/custom': typeof CustomRoute
  '/hair-accessories': typeof HairAccessoriesRoute
  '/keychains': typeof KeychainsRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bouquets': typeof BouquetsRoute
  '/custom': typeof CustomRoute
  '/hair-accessories': typeof HairAccessoriesRoute
  '/keychains': typeof KeychainsRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bouquets'
    | '/custom'
    | '/hair-accessories'
    | '/keychains'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bouquets'
    | '/custom'
    | '/hair-accessories'
    | '/keychains'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/bouquets'
    | '/custom'
    | '/hair-accessories'
    | '/keychains'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BouquetsRoute: typeof BouquetsRoute
  CustomRoute: typeof CustomRoute
  HairAccessoriesRoute: typeof HairAccessoriesRoute
  KeychainsRoute: typeof KeychainsRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/keychains': {
      id: '/keychains'
      path: '/keychains'
      fullPath: '/keychains'
      preLoaderRoute: typeof KeychainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-accessories': {
      id: '/hair-accessories'
      path: '/hair-accessories'
      fullPath: '/hair-accessories'
      preLoaderRoute: typeof HairAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bouquets': {
      id: '/bouquets'
      path: '/bouquets'
      fullPath: '/bouquets'
      preLoaderRoute: typeof BouquetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BouquetsRoute: BouquetsRoute,
  CustomRoute: CustomRoute,
  HairAccessoriesRoute: HairAccessoriesRoute,
  KeychainsRoute: KeychainsRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
